# Generated by Django 6.1 on 2026-08-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sanskrit_name', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('benefits', models.TextField()),
                ('instructions', models.TextField()),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('focus_area', models.CharField(blank=True, max_length=150)),
                ('contraindications', models.TextField(blank=True)),
                ('modifications', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
