# Generated by Django 6.1 on 2026-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asana',
            name='energy_level',
            field=models.CharField(default='Moderate', max_length=30),
        ),
        migrations.AddField(
            model_name='asana',
            name='mood_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
