# Generated by Django 6.1 on 2026-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0002_asana_energy_level_asana_mood_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('menstrual', 'Menstrual'), ('follicular', 'Follicular'), ('ovulation', 'Ovulation'), ('luteal', 'Luteal')], max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('energy_context', models.CharField(max_length=100)),
                ('practice_style', models.CharField(max_length=100)),
                ('intensity', models.CharField(max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('safety_guidance', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
