# Generated by Django 6.1 on 2026-08-19 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0003_cyclephase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('modification_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_recommendations', to='yoga.asana')),
                ('cycle_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='yoga.cyclephase')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'constraints': [models.UniqueConstraint(fields=('cycle_phase', 'asana'), name='unique_cycle_phase_asana')],
            },
        ),
    ]
