# Generated by Django 6.1 on 2026-08-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0004_cyclerecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepDiveFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('energy_context', models.CharField(blank=True, max_length=100)),
                ('practice_style', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('guidance', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
