# Generated by Django 6.1 on 2026-08-21 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0005_deepdivefocus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepDiveRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('guidance_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_dive_recommendations', to='yoga.asana')),
                ('deep_dive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='yoga.deepdivefocus')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'constraints': [models.UniqueConstraint(fields=('deep_dive', 'asana'), name='unique_deep_dive_asana')],
            },
        ),
    ]
