# Generated by Django 6.1 on 2026-09-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0006_deepdiverecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pranayama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sanskrit_name', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('benefits', models.TextField()),
                ('instructions', models.TextField()),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('breathing_pattern', models.CharField(blank=True, max_length=150)),
                ('focus_area', models.CharField(blank=True, max_length=150)),
                ('mood_tags', models.JSONField(blank=True, default=list)),
                ('contraindications', models.TextField(blank=True)),
                ('modifications', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('video_type', models.CharField(default='youtube', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asana',
            name='video_type',
            field=models.CharField(default='youtube', max_length=30),
        ),
        migrations.AddField(
            model_name='asana',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
