# Generated by Django 6.1 on 2026-10-03 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0007_pranayama_asana_video_type_asana_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('asana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_sessions', to='yoga.asana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoga_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
