# Generated by Django 6.1 on 2026-10-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0008_yogasession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asana',
            name='video_type',
        ),
        migrations.RemoveField(
            model_name='asana',
            name='video_url',
        ),
        migrations.AddField(
            model_name='asana',
            name='youtube_channel_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='asana',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asana',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asana',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
