# Generated by Django 6.1 on 2026-10-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0009_remove_asana_video_type_remove_asana_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asana',
            name='alignment_tips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asana',
            name='key_muscles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asana',
            name='precautions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asana',
            name='step_by_step',
            field=models.TextField(blank=True),
        ),
    ]
