# Generated by Django 6.1 on 2026-10-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0010_asana_alignment_tips_asana_key_muscles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asana',
            name='image_url',
        ),
        migrations.AddField(
            model_name='asana',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yoga/asanas/images/'),
        ),
        migrations.AddField(
            model_name='asana',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='yoga/asanas/videos/'),
        ),
    ]
