# Generated by Django 6.1 on 2026-10-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0011_remove_asana_image_url_asana_image_asana_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asana',
            name='youtube_channel_name',
        ),
        migrations.RemoveField(
            model_name='asana',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='asana',
            name='youtube_video_id',
        ),
    ]
