# Generated by Django 6.1 on 2026-10-08 06:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0012_remove_asana_youtube_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asana',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='yoga/asanas/videos/'),
        ),
    ]
