from django.core.management.base import BaseCommand
from yoga.models import Asana


ASANAS = [
    {
        "name": "Tadasana",
        "sanskrit_name": "Tadasana",
        "short_description": "A foundational standing posture that encourages steady alignment and body awareness.",
        "category": "Standing",
        "difficulty": "Beginner",
        "benefits": "Supports posture, balance, grounding, and body awareness.",
        "instructions": "Stand tall with the feet grounded. Lengthen the spine, relax the shoulders, and breathe steadily.",
        "duration_seconds": 30,
        "focus_area": "Full Body",
        "mood_tags": ["low_energy", "stressed"],
        "energy_level": "Low",
        "contraindications": "Practice within your comfort level and use support if balance is difficult.",
        "modifications": "Practice near a wall for additional balance support.",
        "image_url": "",
    },
    {
        "name": "Vrikshasana",
        "sanskrit_name": "Vrikshasana",
        "short_description": "A standing balance posture that develops stability and concentration.",
        "category": "Balance",
        "difficulty": "Beginner",
        "benefits": "Supports balance, concentration, posture, and lower-body stability.",
        "instructions": "Stand tall, shift weight onto one foot, place the other foot in a comfortable supported position, and maintain steady breathing.",
        "duration_seconds": 30,
        "focus_area": "Legs & Balance",
        "mood_tags": ["low_energy"],
        "energy_level": "Moderate",
        "contraindications": "Use support if you have difficulty maintaining balance.",
        "modifications": "Keep the toes of the raised foot on the floor for a lighter variation.",
        "image_url": "",
    },
    {
        "name": "Trikonasana",
        "sanskrit_name": "Trikonasana",
        "short_description": "A standing posture combining lateral movement with active leg engagement.",
        "category": "Standing",
        "difficulty": "Beginner",
        "benefits": "Encourages mobility through the hips, legs, and side body.",
        "instructions": "Take a comfortable wide stance, extend the arms, and gently lengthen the torso sideways while keeping the movement controlled.",
        "duration_seconds": 30,
        "focus_area": "Hips & Side Body",
        "contraindications": "Avoid forcing the range of motion.",
        "modifications": "Place the lower hand on a yoga block or elevated surface.",
        "image_url": "",
    },
    {
        "name": "Virabhadrasana I",
        "sanskrit_name": "Virabhadrasana I",
        "short_description": "A standing posture that combines strength, stability, and focused breathing.",
        "category": "Standing",
        "difficulty": "Beginner",
        "benefits": "Builds lower-body strength and encourages stability and body awareness.",
        "instructions": "Step one foot forward, bend the front knee comfortably, ground through the feet, and lengthen the spine.",
        "duration_seconds": 30,
        "focus_area": "Legs & Core",
        "contraindications": "Keep the stance comfortable and avoid painful knee or hip positions.",
        "modifications": "Use a shorter stance and reduce the knee bend.",
        "image_url": "",
    },
    {
        "name": "Virabhadrasana II",
        "sanskrit_name": "Virabhadrasana II",
        "short_description": "A standing posture emphasizing leg strength, stability, and awareness.",
        "category": "Standing",
        "difficulty": "Beginner",
        "benefits": "Supports leg strength, balance, and mindful movement.",
        "instructions": "Take a wide stance, turn one foot outward, bend the front knee comfortably, and extend the arms.",
        "duration_seconds": 30,
        "focus_area": "Legs & Hips",
        "contraindications": "Avoid forcing the front knee or hip position.",
        "modifications": "Reduce the depth of the front knee bend.",
        "image_url": "",
    },
    {
        "name": "Balasana",
        "sanskrit_name": "Balasana",
        "short_description": "A gentle resting posture commonly used for relaxation and recovery.",
        "category": "Relaxation",
        "difficulty": "Beginner",
        "benefits": "Encourages relaxation and a gentle release through the body.",
        "instructions": "From a kneeling position, lower the hips toward the heels and gently bring the torso forward.",
        "duration_seconds": 60,
        "focus_area": "Back & Hips",
        "mood_tags": ["anxious", "stressed", "cramping"],
        "energy_level": "Low",
        "contraindications": "Choose a comfortable position and avoid pressure that causes discomfort.",
        "modifications": "Place a cushion beneath the hips or torso for additional support.",
        "image_url": "",
    },
    {
        "name": "Bhujangasana",
        "sanskrit_name": "Bhujangasana",
        "short_description": "A gentle backbend practiced with controlled movement and mindful breathing.",
        "category": "Backbend",
        "difficulty": "Beginner",
        "benefits": "Encourages spinal extension and awareness through the front body.",
        "instructions": "Lie on the abdomen, place the hands comfortably, and gently lift the chest while keeping the movement controlled.",
        "duration_seconds": 30,
        "focus_area": "Back & Chest",
        "mood_tags": ["sore", "low_energy"],
        "energy_level": "Moderate",
        "contraindications": "Avoid forcing spinal extension or practicing through pain.",
        "modifications": "Keep the lift low and focus on length rather than height.",
        "image_url": "",
    },
    {
        "name": "Sukhasana",
        "sanskrit_name": "Sukhasana",
        "short_description": "A comfortable seated posture for breathing, mindfulness, and gentle stillness.",
        "category": "Seated",
        "difficulty": "Beginner",
        "benefits": "Supports comfortable seated breathing and mindful awareness.",
        "instructions": "Sit comfortably with the legs crossed, lengthen the spine, relax the shoulders, and breathe naturally.",
        "duration_seconds": 60,
        "focus_area": "Hips & Spine",
        "contraindications": "Choose a comfortable seated position.",
        "modifications": "Sit on a cushion or folded blanket to raise the hips.",
        "image_url": "",
    },
    {
        "name": "Setu Bandhasana",
        "sanskrit_name": "Setu Bandhasana",
        "short_description": "A supported bridge posture that combines gentle strengthening with controlled movement.",
        "category": "Backbend",
        "difficulty": "Beginner",
        "benefits": "Engages the lower body and encourages awareness through the spine and hips.",
        "instructions": "Lie on your back with knees bent, feet grounded, and gently lift the hips while maintaining controlled breathing.",
        "duration_seconds": 30,
        "focus_area": "Hips & Core",
        "contraindications": "Avoid painful movement and keep the range comfortable.",
        "modifications": "Use a smaller lift or practice a supported variation.",
        "image_url": "",
    },
    {
        "name": "Marjaryasana",
        "sanskrit_name": "Marjaryasana",
        "short_description": "A gentle spinal movement performed from a hands-and-knees position.",
        "category": "Mobility",
        "difficulty": "Beginner",
        "benefits": "Encourages gentle spinal mobility and body awareness.",
        "instructions": "Begin on hands and knees and slowly round the spine while coordinating the movement with comfortable breathing.",
        "duration_seconds": 30,
        "focus_area": "Spine",
        "mood_tags": ["sore", "stressed", "wired"],
        "energy_level": "Moderate",
        "contraindications": "Use a comfortable range and avoid painful wrist or knee positions.",
        "modifications": "Place padding under the knees or reduce the movement range.",
        "image_url": "",
    },
    {
        "name": "Bitilasana",
        "sanskrit_name": "Bitilasana",
        "short_description": "A gentle spinal extension movement often paired with Cat Pose.",
        "category": "Mobility",
        "difficulty": "Beginner",
        "benefits": "Supports gentle spinal movement and coordination with breath.",
        "instructions": "From hands and knees, gently lengthen the spine and open through the front body without forcing the movement.",
        "duration_seconds": 30,
        "focus_area": "Spine & Chest",
        "contraindications": "Avoid excessive spinal extension.",
        "modifications": "Use a smaller range of motion.",
        "image_url": "",
    },
    {
        "name": "Adho Mukha Svanasana",
        "sanskrit_name": "Adho Mukha Svanasana",
        "short_description": "A familiar yoga posture combining active support through the hands and legs.",
        "category": "Inversion",
        "difficulty": "Beginner",
        "benefits": "Encourages whole-body engagement and mobility through the back body.",
        "instructions": "From hands and knees, lift the hips upward while maintaining a comfortable spine and steady breathing.",
        "duration_seconds": 30,
        "focus_area": "Full Body",
        "contraindications": "Modify or skip if the position causes discomfort.",
        "modifications": "Keep the knees bent and reduce the depth of the posture.",
        "image_url": "",
    },
    {
        "name": "Paschimottanasana",
        "sanskrit_name": "Paschimottanasana",
        "short_description": "A seated forward-folding posture practiced with a long, comfortable spine.",
        "category": "Forward Bend",
        "difficulty": "Intermediate",
        "benefits": "Encourages gentle mobility through the back body and legs.",
        "instructions": "Sit with the legs extended and gently hinge forward from the hips without forcing the stretch.",
        "duration_seconds": 45,
        "focus_area": "Hamstrings & Back",
        "contraindications": "Avoid forcing the forward fold.",
        "modifications": "Bend the knees or use a strap for support.",
        "image_url": "",
    },
    {
        "name": "Baddha Konasana",
        "sanskrit_name": "Baddha Konasana",
        "short_description": "A seated posture that encourages comfortable hip mobility.",
        "category": "Hip Opener",
        "difficulty": "Beginner",
        "benefits": "Supports gentle hip mobility and relaxed seated movement.",
        "instructions": "Bring the soles of the feet together and allow the knees to move outward comfortably.",
        "duration_seconds": 45,
        "focus_area": "Hips",
        "contraindications": "Do not force the knees downward.",
        "modifications": "Place cushions beneath the knees for support.",
        "image_url": "",
    },
    {
        "name": "Ardha Matsyendrasana",
        "sanskrit_name": "Ardha Matsyendrasana",
        "short_description": "A seated spinal rotation practiced with controlled movement.",
        "category": "Twist",
        "difficulty": "Intermediate",
        "benefits": "Encourages comfortable rotational mobility through the spine.",
        "instructions": "Sit upright and gently rotate the torso while keeping the movement controlled and comfortable.",
        "duration_seconds": 30,
        "focus_area": "Spine",
        "contraindications": "Avoid forcing spinal rotation.",
        "modifications": "Use a smaller rotation and keep the spine comfortably long.",
        "image_url": "",
    },
    {
        "name": "Savasana",
        "sanskrit_name": "Savasana",
        "short_description": "A resting posture used to support relaxation and mindful recovery.",
        "category": "Relaxation",
        "difficulty": "Beginner",
        "benefits": "Encourages relaxation, stillness, and recovery after practice.",
        "instructions": "Lie comfortably on your back, allow the body to relax, and breathe naturally.",
        "duration_seconds": 120,
        "focus_area": "Full Body",
        "mood_tags": ["anxious", "stressed", "wired", "low_energy"],
        "energy_level": "Low",
        "contraindications": "Choose another comfortable resting position if lying on the back is unsuitable.",
        "modifications": "Place a cushion beneath the knees for additional comfort.",
        "image_url": "",
    },
    {
        "name": "Anjaneyasana",
        "sanskrit_name": "Anjaneyasana",
        "short_description": "A gentle lunge posture that encourages mobility through the hips and legs.",
        "category": "Hip Opener",
        "difficulty": "Beginner",
        "benefits": "Supports hip mobility, balance, and lower-body awareness.",
        "instructions": "Step one foot forward and lower the opposite knee comfortably while keeping the torso upright.",
        "duration_seconds": 30,
        "focus_area": "Hips & Legs",
        "contraindications": "Keep the movement comfortable around the knees and hips.",
        "modifications": "Place padding beneath the back knee.",
        "image_url": "",
    },
    {
        "name": "Utkatasana",
        "sanskrit_name": "Utkatasana",
        "short_description": "A standing posture that develops lower-body engagement and stability.",
        "category": "Strength",
        "difficulty": "Beginner",
        "benefits": "Builds awareness and strength through the legs and core.",
        "instructions": "Stand with the feet grounded, bend the knees comfortably, and lower the hips while maintaining a long spine.",
        "duration_seconds": 30,
        "focus_area": "Legs & Core",
        "contraindications": "Avoid uncomfortable knee or hip positions.",
        "modifications": "Use a smaller knee bend or practice near a wall.",
        "image_url": "",
    },
    {
        "name": "Garudasana",
        "sanskrit_name": "Garudasana",
        "short_description": "A balance posture combining concentration with coordinated positioning.",
        "category": "Balance",
        "difficulty": "Intermediate",
        "benefits": "Challenges balance, coordination, and concentration.",
        "instructions": "Stand steadily and gradually explore the crossed-leg and arm positions while maintaining comfortable breathing.",
        "duration_seconds": 30,
        "focus_area": "Balance & Focus",
        "contraindications": "Use support if balance is uncertain.",
        "modifications": "Keep the toes of the raised foot lightly touching the floor.",
        "image_url": "",
    },
    {
        "name": "Matsyasana",
        "sanskrit_name": "Matsyasana",
        "short_description": "A reclining posture involving gentle opening through the front body.",
        "category": "Backbend",
        "difficulty": "Intermediate",
        "benefits": "Encourages awareness through the chest and upper body.",
        "instructions": "Settle into a supported reclining position and gently open through the front body without forcing the neck.",
        "duration_seconds": 30,
        "focus_area": "Chest & Upper Back",
        "contraindications": "Avoid uncomfortable neck or back positions.",
        "modifications": "Practice with supportive cushions rather than forcing the posture.",
        "image_url": "",
    },
]


class Command(BaseCommand):
    help = "Seed the database with initial yoga asanas"

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for data in ASANAS:
            asana, created = Asana.objects.update_or_create(
                name=data["name"],
                defaults=data,
            )

            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seed complete: {created_count} created, "
                f"{updated_count} updated."
            )
        )