# Generated by Django 6.1 on 2026-09-06 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('mindfulness', 'Mindfulness'), ('breath_awareness', 'Breath Awareness'), ('stress_relief', 'Stress Relief'), ('focus_clarity', 'Focus & Clarity'), ('sleep', 'Sleep Meditation'), ('loving_kindness', 'Loving-Kindness')], max_length=50)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
